### ISSUE TITLE
Bug Report: Fail to sign multiple transactions consecutively

### ISSUE THREAD

**Issue by ColinWttt** [Consensys/starknet-snap#150]
Bug: When signing multiple transactions in succession manually, the second and subsequent transactions fail after signing. After some time, I am able to successfully sign transactions.

This error can be reproduced on [snaps.consensys.net/starknet](https://snaps.consensys.net/starknet), when you send tokens consecutively, the second one fails.

[![error.png](https://i.postimg.cc/jdLJKZzZ/error.png)](https://postimg.cc/gnb0HytZ)

console log two types of errors randomly
error1: MetaMask - RPC Error: 59: A transaction with the same hash already exists in the mempool

error2: MetaMask - RPC Error: 52: Invalid transaction nonce
[![error52.png](https://i.postimg.cc/fRSX7ByJ/error52.png)](https://postimg.cc/rDcKMGSk)

starknet-snap version: @consensys/starknet-snap 2.2.0

MetaMask version: 11.0.0

Chrome: 117.0.5938.92 (arm 64)

Network: Starknet Goerli Testnet

**Comment by stanleyyconsensys** [comment]
the issue was introduced when the transaction has sent, but it is still pending at the block, hence the latest block nonce is not updated on chain.

when we send another transaction in between the nonce update, it will occur such issue

we can resolve the issue by 
Opt1 : adding a wait for transaction to block the UI 
Opt2 : increment the nonce by adding a memory store to remember the last nonce from snap
Opt3 : retry the request with nonce increment when it has nonce error

**Comment by japuiglaucia** [comment]
Bug Report: Fail to sign multiple transactions consecutively #150

**Comment by Spunsd** [comment]
Hello

**Comment by vivek-consensys** [comment]
Tested the fix by @khanti42 on dev and the user is able to sign multiple transactions consecutively. 
![image](https://github.com/user-attachments/assets/dcdc4c98-716e-4f7e-a3dd-2c5b4c71af15)
